name: deploy

concurrency: deploy

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@dfdfedc86b296f5e5384f755a18bf400409a15d0

      - name: deploy host-app
        run: flyctl deploy --remote-only ./host-app
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: deploy remote-app-1
        run: flyctl deploy --remote-only ./remote-app-1
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: deploy remote-app-2
        run: flyctl deploy --remote-only ./remote-app-2
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
